[package]
name = "ace_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7"
log = "0.4"
deno_core = "0.140"
anyhow = "1.0"
serde = "1.0"
serde_json = "1"
handlebars = "4"
ace_components = { path = "../ace_components" }